"""initial_schema

Revision ID: f0b77beb14c5
Revises: 
Create Date: 2026-06-20 00:40:35.748333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b77beb14c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('note_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('tag_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('tag_filter', sa.String(), nullable=True),
    sa.Column('cards_reviewed', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_type', sa.String(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('user_annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('annotation_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tags',
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_type', 'item_id', 'tag_id')
    )
    op.create_index('idx_item_tags_item', 'item_tags', ['item_type', 'item_id'], unique=False)
    op.create_index('idx_item_tags_tag', 'item_tags', ['tag_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('topic_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_doc', 'notes', ['document_id'], unique=False)
    op.create_index('idx_notes_topic_order', 'notes', ['topic_order'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('order_in_doc', sa.Integer(), nullable=True),
    sa.Column('bookmarked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_doc', 'questions', ['document_id'], unique=False)
    op.create_table('srs_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index('idx_srs_due', 'srs_cards', ['due_date'], unique=False)
    op.create_table('srs_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['srs_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_card', 'srs_reviews', ['card_id'], unique=False)
    op.create_index('idx_reviews_date', 'srs_reviews', ['reviewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_date', table_name='srs_reviews')
    op.drop_index('idx_reviews_card', table_name='srs_reviews')
    op.drop_table('srs_reviews')
    op.drop_index('idx_srs_due', table_name='srs_cards')
    op.drop_table('srs_cards')
    op.drop_index('idx_questions_doc', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_notes_topic_order', table_name='notes')
    op.drop_index('idx_notes_doc', table_name='notes')
    op.drop_table('notes')
    op.drop_index('idx_item_tags_tag', table_name='item_tags')
    op.drop_index('idx_item_tags_item', table_name='item_tags')
    op.drop_table('item_tags')
    op.drop_table('user_annotations')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('study_sessions')
    op.drop_table('documents')
    # ### end Alembic commands ###
